import { Canvas } from '@react-three/fiber'
import { useGLTF, AccumulativeShadows, RandomizedLight, CameraControls, Center } from '@react-three/drei'
import { EffectComposer, Bloom, ToneMapping } from '@react-three/postprocessing'

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 the_halloween_cat.glb --transform
Author: Enkarra (https://sketchfab.com/Enkarra)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-halloween-cat-dba541e7635c49f190e2a32d9e67c6f9
Title: The Halloween cat
*/

function Model(props) {
  const { nodes, materials } = useGLTF('/the_halloween_cat-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        {/** Tonemapping on the glowing materials needs to be switched off bc it would clip RGB at 0-1,
         /*  Any color that leaves the 0-1 spectrum will now glow, for instance by setting emissiveIntensity > 1 */}
        <mesh castShadow geometry={nodes.Object_2.geometry} material={materials.eyes_LPSG} material-toneMapped={false} material-emissiveIntensity={10} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.initialShadingGroup} material-toneMapped={false} material-emissiveIntensity={10} />
      </group>
    </group>
  )
}

export default function App() {
  return (
    <Canvas shadows camera={{ position: [0, 1, 5] }}>
      <color attach="background" args={['#252530']} />
      <hemisphereLight color="blue" groundColor="red" intensity={0.5} />
      <spotLight position={[10, 10, 10]} angle={0.15} penumbra={1} />
      <pointLight position={[0, -1.35, 0]} color="orange" intensity={25} distance={2} />
      <Center>
        <Model scale={0.01} />
      </Center>
      <AccumulativeShadows position={[0, -2.24, 0]} temporal frames={100} alphaTest={0.9} opacity={1.5} scale={12}>
        <RandomizedLight amount={8} radius={2} ambient={0.5} intensity={1} position={[-2.5, 5, 0.5]} bias={0.001} />
      </AccumulativeShadows>
      <EffectComposer disableNormalPass>
        {/** The bloom pass is what will create glow, always set the threshold to 1, nothing will glow
         /*  except materials without tonemapping whose colors leave RGB 0-1 */}
        <Bloom mipmapBlur luminanceThreshold={1} />
        <ToneMapping adaptive resolution={256} middleGrey={0.4} maxLuminance={16.0} averageLuminance={1.0} adaptationRate={1.0} />
      </EffectComposer>
      <CameraControls />
    </Canvas>
  )
}
